DROP TABLE IF EXISTS CAR;

CREATE TABLE CAR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  make VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  colour VARCHAR(250) NOT NULL,
  year int(250) NOT NULL
);